// preset/templates/angular/views/hello/index.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "app-hello",
    templateUrl: "./index.component.html",
})
export default class HelloComponent {}

<div class="h-full flex justify-center items-center flex-col gap-10">
    <img src="favicon.ico" class="max-w-[30%]" />
    <p>Hello Angular!</p>
</div>

// preset/templates/react/views/Hello.tsx
import { Component, ReactNode } from "react";

export default class Hello extends Component {
    render(): ReactNode {
        return (
            <div className="h-full flex justify-center items-center flex-col gap-10">
                <img src="favicon.ico" className="max-w-[30%]" />
                <p>Hello React!</p>
            </div>
        );
    }
}
